USE PH_MV

CREATE TABLE MEMBERS (
	MEMBER_ID INT IDENTITY(1000,1) PRIMARY KEY, 
	GROUP_ID INT,
	STAGE_NAME VARCHAR(30) NOT NULL,
	FULL_NAME VARCHAR(50) NOT NULL,
	POSITION VARCHAR(25),
	BIRTHDAY DATE
)

ALTER TABLE MEMBERS  WITH CHECK ADD 
	CONSTRAINT	[FK_MEMBERS_GROUP_ID_TO_ARTIST_GROUP_ID]
	FOREIGN KEY	(GROUP_ID)
	REFERENCES	ARTIST (GROUP_ID)