USE PH_MV

CREATE TABLE SHOW_EVENTS (
	EVENT_ID INT IDENTITY(1000,1) PRIMARY KEY, 
	GROUP_ID INT,
	EVENT_NAME VARCHAR(30) NOT NULL,
	EVENT_TYPE VARCHAR(20), 
	VENUE VARCHAR(50) NOT NULL,
	EVENT_DATETIME DATETIME
)

ALTER TABLE SHOW_EVENTS WITH CHECK ADD
	CONSTRAINT	[FK_SHOW_EVENTS_GROUP_ID_TO_ARTIST_GROUP_ID]
	FOREIGN KEY (GROUP_ID)
	REFERENCES	ARTIST (GROUP_ID)