USE PH_MV

CREATE TABLE SONG (
	SONG_ID INT IDENTITY(1000,1) PRIMARY KEY, 
	GROUP_ID INT,
	TITLE VARCHAR(30) NOT NULL,
	RELEASE_DATE DATETIME,
	COMPOSER VARCHAR(30) NOT NULL
)

ALTER TABLE SONG WITH CHECK ADD
	CONSTRAINT	[FK_SONGS_GROUP_ID_TO_ARTIST_GROUP_ID]
	FOREIGN KEY (GROUP_ID)
	REFERENCES	ARTIST (GROUP_ID)