USE PH_MV

CREATE TABLE VOTE (
	VOTE_ID INT IDENTITY(1000,1) PRIMARY KEY, 
	SONG_ID INT NOT NULL,
	MONTH_YEAR DATE NOT NULL,
	VOTE_COUNT INT DEFAULT 0
)

ALTER TABLE SONG WITH CHECK ADD
	CONSTRAINT	[FK_VOTE_SONG_ID_TO_SONG_SONG_ID]
	FOREIGN KEY (SONG_ID)
	REFERENCES	SONG (SONG_ID)

ALTER TABLE VOTE
ADD CONSTRAINT UQ_SONG_MONTH UNIQUE (SONG_ID, MONTH_YEAR);
