SELECT VOTE_ID, v.SONG_ID,s.TITLE, MONTH_YEAR, VOTE_COUNT
FROM VOTE v JOIN SONG s on s.SONG_ID = v.SONG_ID
WHERE MONTH(MONTH_YEAR) = MONTH(GETDATE())
AND YEAR(MONTH_YEAR) = YEAR(GETDATE())
ORDER BY v.VOTE_COUNT Desc; 